# Generated by Django 5.0 on 2023-12-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(unique=True)),
                ('nama', models.TextField(max_length=100)),
                ('nama_latin', models.TextField(max_length=100)),
                ('jumlah_ayat', models.IntegerField()),
                ('tempat_turun', models.TextField()),
                ('arti', models.TextField()),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_ayat', models.IntegerField()),
                ('teks_arab', models.TextField()),
                ('teks_latin', models.TextField()),
                ('teks_indo', models.TextField()),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayat_links', to='main.surat')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versi', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_links', to='main.surat')),
            ],
        ),
    ]
